title: Technical documentation
description: Technical documentation of VSDS

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true



nav_external_links:
  - title: VSDS Technical Docs
    url: https://informatievlaanderen.github.io/VSDS-Tech-Docs/
    hide_icon: false # set to true to hide the external link icon - defaults to false

enable_copy_code_button: true

footer_content: "Technical documentation of the <a href=\"https://www.vlaanderen.be/vlaamse-smart-data-space-portaal/\">Flanders Smart Data Space.</a>"


plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
