title: Technical documentation
description: Technical documentation of VSDS

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true


aux_links:
  LDI Repository: https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions

# Define Jekyll collections
collections:
  ldesclient:
    permalink: "/:collection/:path"
    output: true


just_the_docs:
  collections:
    ldesclient:
      name: LDES Client


nav_external_links:
  - title: VSDS Technical Docs
    url: https://informatievlaanderen.github.io/VSDS-Tech-Docs/
    hide_icon: false # set to true to hide the external link icon - defaults to false

enable_copy_code_button: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
